"""Build a decade-wide source-field inventory from the coverage audit.

Input is the read-only ``data/source_field_coverage.csv`` generated by
``audit_source_field_coverage.py``. The output preserves empirical coverage
without changing canonical data.
"""
from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent
INPUT = ROOT / "data" / "source_field_coverage.csv"
OUTPUT = ROOT / "data" / "source_field_decade_inventory.csv"


def build() -> int:
    if not INPUT.is_file():
        raise FileNotFoundError(f"Coverage audit not found: {INPUT}")

    grouped: dict[tuple[str, str], set[str]] = defaultdict(set)
    with INPUT.open("r", encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(handle):
            if row.get("presence") != "PRESENT":
                continue
            family = row.get("source_family", "")
            field = row.get("source_field", "")
            season = row.get("season", "")
            if family and field and season:
                grouped[(family, field)].add(season)

    seasons = sorted({season for values in grouped.values() for season in values})
    rows = []
    for (family, field), present in sorted(grouped.items()):
        count = len(present)
        if count == len(seasons):
            coverage_class = "CORE_DECADE"
        elif count >= max(2, len(seasons) // 2):
            coverage_class = "LONG_RUN"
        elif count > 1:
            coverage_class = "INTERMITTENT"
        else:
            coverage_class = "SINGLE_SEASON"
        rows.append({
            "source_family": family,
            "source_field": field,
            "seasons_present": count,
            "first_seen_season": min(present),
            "last_seen_season": max(present),
            "coverage_class": coverage_class,
            "seasons_present_list": ", ".join(sorted(present)),
        })

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w", encoding="utf-8-sig", newline="") as handle:
        columns = [
            "source_family",
            "source_field",
            "seasons_present",
            "first_seen_season",
            "last_seen_season",
            "coverage_class",
            "seasons_present_list",
        ]
        writer = csv.DictWriter(handle, fieldnames=columns)
        writer.writeheader()
        writer.writerows(rows)

    return len(rows)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.parse_args()
    count = build()
    print(f"SOURCE FIELD INVENTORY: {count} unique source fields written")
    print(f"Output: {OUTPUT}")
