/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited directly.
// It is generated by Next.js and retained in source control for TypeScript tooling.
